package sistemahotel.entity;
// Generated 8/11/2019 10:16:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private String cliNombre;
     private String cliApellido;
     private String cliTelefono;
     private String cliDireccion;
     private String cliCalle;
     private String cliColonia;
     private String cliCuidad;
     private Set reservacions = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String cliNombre, String cliApellido, String cliTelefono, String cliDireccion, String cliCalle, String cliColonia, String cliCuidad) {
        this.cliNombre = cliNombre;
        this.cliApellido = cliApellido;
        this.cliTelefono = cliTelefono;
        this.cliDireccion = cliDireccion;
        this.cliCalle = cliCalle;
        this.cliColonia = cliColonia;
        this.cliCuidad = cliCuidad;
    }
    public Cliente(String cliNombre, String cliApellido, String cliTelefono, String cliDireccion, String cliCalle, String cliColonia, String cliCuidad, Set reservacions) {
       this.cliNombre = cliNombre;
       this.cliApellido = cliApellido;
       this.cliTelefono = cliTelefono;
       this.cliDireccion = cliDireccion;
       this.cliCalle = cliCalle;
       this.cliColonia = cliColonia;
       this.cliCuidad = cliCuidad;
       this.reservacions = reservacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCliNombre() {
        return this.cliNombre;
    }
    
    public void setCliNombre(String cliNombre) {
        this.cliNombre = cliNombre;
    }
    public String getCliApellido() {
        return this.cliApellido;
    }
    
    public void setCliApellido(String cliApellido) {
        this.cliApellido = cliApellido;
    }
    public String getCliTelefono() {
        return this.cliTelefono;
    }
    
    public void setCliTelefono(String cliTelefono) {
        this.cliTelefono = cliTelefono;
    }
    public String getCliDireccion() {
        return this.cliDireccion;
    }
    
    public void setCliDireccion(String cliDireccion) {
        this.cliDireccion = cliDireccion;
    }
    public String getCliCalle() {
        return this.cliCalle;
    }
    
    public void setCliCalle(String cliCalle) {
        this.cliCalle = cliCalle;
    }
    public String getCliColonia() {
        return this.cliColonia;
    }
    
    public void setCliColonia(String cliColonia) {
        this.cliColonia = cliColonia;
    }
    public String getCliCuidad() {
        return this.cliCuidad;
    }
    
    public void setCliCuidad(String cliCuidad) {
        this.cliCuidad = cliCuidad;
    }
    public Set getReservacions() {
        return this.reservacions;
    }
    
    public void setReservacions(Set reservacions) {
        this.reservacions = reservacions;
    }




}


