package sistemahotel.entity;
// Generated 8/11/2019 10:16:25 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private Integer id;
     private String pueNombre;
     private BigDecimal pueSueldo;
     private Set personals = new HashSet(0);

    public Puesto() {
    }

	
    public Puesto(String pueNombre, BigDecimal pueSueldo) {
        this.pueNombre = pueNombre;
        this.pueSueldo = pueSueldo;
    }
    public Puesto(String pueNombre, BigDecimal pueSueldo, Set personals) {
       this.pueNombre = pueNombre;
       this.pueSueldo = pueSueldo;
       this.personals = personals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPueNombre() {
        return this.pueNombre;
    }
    
    public void setPueNombre(String pueNombre) {
        this.pueNombre = pueNombre;
    }
    public BigDecimal getPueSueldo() {
        return this.pueSueldo;
    }
    
    public void setPueSueldo(BigDecimal pueSueldo) {
        this.pueSueldo = pueSueldo;
    }
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }




}


