package sistemahotel.entity;
// Generated 8/11/2019 10:16:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservacion generated by hbm2java
 */
public class Reservacion  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private Recepcionista recepcionista;
     private Date resEntradaCli;
     private Date resSalidaCli;
     private Date resFecha;
     private int resNumPersonas;
     private int resNumCuarto;
     private float resPago;
     private Date resHoraLlegada;

    public Reservacion() {
    }

    public Reservacion(Cliente cliente, Recepcionista recepcionista, Date resEntradaCli, Date resSalidaCli, Date resFecha, int resNumPersonas, int resNumCuarto, float resPago, Date resHoraLlegada) {
       this.cliente = cliente;
       this.recepcionista = recepcionista;
       this.resEntradaCli = resEntradaCli;
       this.resSalidaCli = resSalidaCli;
       this.resFecha = resFecha;
       this.resNumPersonas = resNumPersonas;
       this.resNumCuarto = resNumCuarto;
       this.resPago = resPago;
       this.resHoraLlegada = resHoraLlegada;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Recepcionista getRecepcionista() {
        return this.recepcionista;
    }
    
    public void setRecepcionista(Recepcionista recepcionista) {
        this.recepcionista = recepcionista;
    }
    public Date getResEntradaCli() {
        return this.resEntradaCli;
    }
    
    public void setResEntradaCli(Date resEntradaCli) {
        this.resEntradaCli = resEntradaCli;
    }
    public Date getResSalidaCli() {
        return this.resSalidaCli;
    }
    
    public void setResSalidaCli(Date resSalidaCli) {
        this.resSalidaCli = resSalidaCli;
    }
    public Date getResFecha() {
        return this.resFecha;
    }
    
    public void setResFecha(Date resFecha) {
        this.resFecha = resFecha;
    }
    public int getResNumPersonas() {
        return this.resNumPersonas;
    }
    
    public void setResNumPersonas(int resNumPersonas) {
        this.resNumPersonas = resNumPersonas;
    }
    public int getResNumCuarto() {
        return this.resNumCuarto;
    }
    
    public void setResNumCuarto(int resNumCuarto) {
        this.resNumCuarto = resNumCuarto;
    }
    public float getResPago() {
        return this.resPago;
    }
    
    public void setResPago(float resPago) {
        this.resPago = resPago;
    }
    public Date getResHoraLlegada() {
        return this.resHoraLlegada;
    }
    
    public void setResHoraLlegada(Date resHoraLlegada) {
        this.resHoraLlegada = resHoraLlegada;
    }




}


